import Head from 'next/head'
import Hero from '../components/HeroSection'
import FAQ from '../components/Home/FAQ'
import IconCards from '../components/Home/IconCards'
import PartnerSection from '../components/Home/PartnerSection'
import Testionials from '../components/Home/Testionials'
import HomeCarousel from '../components/Home/utility/Carousel'
import { content } from '../content'

const homeContent = { ...content.homePage }


export default function Home() {
  return (
    <div>
      <Head>
        <title>RootLevel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <Hero
        {...homeContent.heroSection}
      />
      <PartnerSection />
      <IconCards />
      <Testionials />
      <FAQ />
    </div>
  )
}
