import Head from 'next/head'
import Hero from '../components/HeroSection'
import FAQ from '../components/Home/FAQ'
import IconCards from '../components/Home/IconCards'
import PartnerSection from '../components/Home/PartnerSection'
import Testimonials from '../components/Home/Testimonials'
import { content } from '../content'

const homeContent = { ...content.homePage }
const questionAnswer = [...homeContent.faqs]
const iconCardContent = [...homeContent.cardContent]

export default function Home() {
  return (
    <div>
      <Head>
        <title>RootLevel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <Hero
        {...homeContent.heroSection}
      // imageProps={{ imageURL: "https://images.unsplash.com/photo-1517339461380-928f5f4def9b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=752&q=80" }}
      />
      <PartnerSection />
      <IconCards cardContent={iconCardContent} />
      <Testimonials />
      <FAQ questionAnswer={questionAnswer} />
    </div>
  )
}
